## Numpy Multidimensional Array Object

In [22]:
import numpy as np

data1 = [6, 7.8, 8, 0, 1]
data2 = [3, 2, 10, 5, 1]
arr1 = np.array(data1)
arr2 = np.array(data2, dtype=np.float64)

print(arr1)
print(10 *arr1)
print(arr1.dtype)
print(arr1.ndim)
print(arr1.shape)

data_sum = data1 + data2
print("data_sum : ", data_sum)
numpy_sum = arr1 + arr2
print("numpy_sum : ", numpy_sum)
#numpy_append = np.append(arr1, arr2)
#print("numpy append : ", numpy_append)
numpy_transpose = np.transpose(arr1)
print("numpy_transpose : ", numpy_transpose)
print("samae, numpy_transpose : ", arr1.T)

[6.  7.8 8.  0.  1. ]
[60. 78. 80.  0. 10.]
float64
1
(5,)
data_sum :  [6, 7.8, 8, 0, 1, 3, 2, 10, 5, 1]
numpy_sum :  [ 9.   9.8 18.   5.   2. ]
numpy_transpose :  [6.  7.8 8.  0.  1. ]
samae, numpy_transpose :  [6.  7.8 8.  0.  1. ]


???output of transpose looked a bit weird...but going to understand it for make it readable

In [25]:
ten_arr = np.array(data_sum)
ten_arr.resize((2,5))
print("ten_arr resize: \n", ten_arr)

#is it possible?
ten_arr.resize((3,3))
print("ten_arr resize to 3x3 : \n", ten_arr)

ten_arr resize: 
 [[ 6.   7.8  8.   0.   1. ]
 [ 3.   2.  10.   5.   1. ]]
ten_arr resize to 3x3 : 
 [[ 6.   7.8  8. ]
 [ 0.   1.   3. ]
 [ 2.  10.   5. ]]


In [26]:
print(ten_arr[ten_arr<5])


[0. 1. 3. 2.]


In [27]:
np.split(ten_arr, 3)

[array([[6. , 7.8, 8. ]]), array([[0., 1., 3.]]), array([[ 2., 10.,  5.]])]

## Matrix Calculation

In [7]:
import numpy as np

data1 = [[1, 2, 3, 4],[5,6,7,8]]
data2 = [[1,2],[3,4],[5,6],[7,8]]
arr1 = np.array(data1)
arr2 = np.array(data2, dtype=np.float64)

multi_arr = arr1 * arr1
dot_arr = np.dot(arr1, arr2)

print(multi_arr)
print(dot_arr)

[[ 1  4  9 16]
 [25 36 49 64]]
[[ 50.  60.]
 [114. 140.]]


In [9]:
arr1_trans = arr1.transpose()
print(np.dot(arr1_trans, arr1))

[[26 32 38 44]
 [32 40 48 56]
 [38 48 58 68]
 [44 56 68 80]]


## Inverting Matrix

In [18]:

c = np.array([[1,2,3,4],[5,6,7,8],[9,0,1,1],[13,7,2,6]])
inv_c = np.linalg.inv(c)
print(inv_c, "\n")

print(np.dot(c, inv_c), "\n")

[[-0.0467033   0.00274725  0.0989011   0.01098901]
 [-0.62362637  0.27197802 -0.20879121  0.08791209]
 [-0.61263736  0.4478022   0.12087912 -0.20879121]
 [ 1.03296703 -0.47252747 -0.01098901  0.10989011]] 

[[ 1.00000000e+00  2.22044605e-16  2.08166817e-17  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  5.55111512e-17  0.00000000e+00]
 [ 4.44089210e-16 -2.77555756e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -2.22044605e-16 -5.89805982e-17  1.00000000e+00]] 



Some element which should be 0 have a very small value.
This is due to numerical precision issues.
Numpy does not make symbolic computations like Mathmatica or sympy,
it deals with numbers up to a certain precision

In [19]:
print(arr1, "\n")
print(np.sum(arr1))

[[1 2 3 4]
 [5 6 7 8]] 

36


## Mathmatical Operations

In [20]:
D = np.exp(arr1)
E = np.cos(arr1)
F = np.log(arr1)
G = (arr1 + 3) * np.cos(arr1 -2)

print(D, "\n")
print(E, "\n")
print(F, "\n")
print(G, "\n")

[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]] 

[[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
 [ 0.28366219  0.96017029  0.75390225 -0.14550003]] 

[[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154]] 

[[ 2.16120922  5.          3.24181384 -2.91302786]
 [-7.91993997 -5.88279259  2.83662185 10.56187315]] 

